import 'package:econa_mobile_app/domains/entities/profile_label_keys.dart';
import 'package:econa_mobile_app/i18n/strings.g.dart';

String localizeLabel(
  LabelKey key, {
  bool? isMale,
}) {
  switch (key.value) {
    // BloodType
    case 'profile.bloodType.a':
      return t.profile.bloodType.a;
    case 'profile.bloodType.b':
      return t.profile.bloodType.b;
    case 'profile.bloodType.ab':
      return t.profile.bloodType.ab;
    case 'profile.bloodType.o':
      return t.profile.bloodType.o;
    case 'profile.bloodType.unknown':
      return t.profile.bloodType.unknown;

    // Holiday
    case 'profile.holiday.weekend':
      return t.profile.holiday.weekend;
    case 'profile.holiday.weekday':
      return t.profile.holiday.weekday;
    case 'profile.holiday.irregular':
      return t.profile.holiday.irregular;
    case 'profile.holiday.other':
      return t.profile.holiday.other;

    // MaritalHistory
    case 'profile.maritalHistory.neverMarried':
      return t.profile.maritalHistory.neverMarried;
    case 'profile.maritalHistory.divorced':
      return t.profile.maritalHistory.divorced;
    case 'profile.maritalHistory.widowed':
      return t.profile.maritalHistory.widowed;
    case 'profile.maritalHistory.other':
      return t.profile.maritalHistory.other;

    // ChildSituation
    case 'profile.childSituation.none':
      return t.profile.childSituation.none;
    case 'profile.childSituation.livingTogether':
      return t.profile.childSituation.livingTogether;
    case 'profile.childSituation.livingApart':
      return t.profile.childSituation.livingApart;
    case 'profile.childSituation.unspecified':
      return t.profile.childSituation.unspecified;

    // DrinkingAlcohol
    case 'profile.drinkingAlcohol.nonDrinker':
      return t.profile.drinkingAlcohol.nonDrinker;
    case 'profile.drinkingAlcohol.regularDrinker':
      return t.profile.drinkingAlcohol.regularDrinker;
    case 'profile.drinkingAlcohol.occasionalDrinker':
      return t.profile.drinkingAlcohol.occasionalDrinker;
    case 'profile.drinkingAlcohol.socialDrinker':
      return t.profile.drinkingAlcohol.socialDrinker;

    // Smoking
    case 'profile.smoking.nonSmoker':
      return t.profile.smoking.nonSmoker;
    case 'profile.smoking.smoker':
      return t.profile.smoking.smoker;
    case 'profile.smoking.eCigaretteSmoker':
      return t.profile.smoking.eCigaretteSmoker;
    case 'profile.smoking.considerateSmoker':
      return t.profile.smoking.considerateSmoker;
    case 'profile.smoking.flexibleSmoker':
      return t.profile.smoking.flexibleSmoker;
    case 'profile.smoking.occasionalSmoker':
      return t.profile.smoking.occasionalSmoker;
    case 'profile.smoking.unspecified':
      return t.profile.smoking.unspecified;

    // MarriageAspiration
    case 'profile.marriageAspiration.asap':
      return t.profile.marriageAspiration.asap;
    case 'profile.marriageAspiration.twoToThreeYears':
      return t.profile.marriageAspiration.twoToThreeYears;
    case 'profile.marriageAspiration.ifRightPerson':
      return t.profile.marriageAspiration.ifRightPerson;
    case 'profile.marriageAspiration.discussWithPartner':
      return t.profile.marriageAspiration.discussWithPartner;
    case 'profile.marriageAspiration.unsure':
      return t.profile.marriageAspiration.unsure;

    // ChildDesire
    case 'profile.childDesire.wantChildren':
      return t.profile.childDesire.wantChildren;
    case 'profile.childDesire.noChildren':
      return t.profile.childDesire.noChildren;
    case 'profile.childDesire.discussWithPartner':
      return t.profile.childDesire.discussWithPartner;
    case 'profile.childDesire.unsure':
      return t.profile.childDesire.unsure;

    // FirstDate cost
    case 'profile.firstDatePreference.cost.discussWithPartner':
      return t.profile.firstDatePreference.cost.discussWithPartner;
    case 'profile.firstDatePreference.cost.iPayAll':
      return t.profile.firstDatePreference.cost.iPayAll;
    case 'profile.firstDatePreference.cost.iPayMore':
      return t.profile.firstDatePreference.cost.iPayMore;
    case 'profile.firstDatePreference.cost.splitEqually':
      return t.profile.firstDatePreference.cost.splitEqually;
    case 'profile.firstDatePreference.cost.partnerPayAll':
      return t.profile.firstDatePreference.cost.partnerPayAll;
    case 'profile.firstDatePreference.cost.partnerPayMore':
      return t.profile.firstDatePreference.cost.partnerPayMore;
    case 'profile.firstDatePreference.cost.wealthierPays':
      return t.profile.firstDatePreference.cost.wealthierPays;

    // FirstDate place
    case 'profile.firstDatePreference.place.park':
      return t.profile.firstDatePreference.place.park;
    case 'profile.firstDatePreference.place.cafe':
      return t.profile.firstDatePreference.place.cafe;
    case 'profile.firstDatePreference.place.restaurant':
      return t.profile.firstDatePreference.place.restaurant;
    case 'profile.firstDatePreference.place.movieTheater':
      return t.profile.firstDatePreference.place.movieTheater;
    case 'profile.firstDatePreference.place.amusementPark':
      return t.profile.firstDatePreference.place.amusementPark;
    case 'profile.firstDatePreference.place.museum':
      return t.profile.firstDatePreference.place.museum;
    case 'profile.firstDatePreference.place.partnersChoice':
      return t.profile.firstDatePreference.place.partnersChoice;

    // Occupation
    case 'profile.occupation.listedCompany':
      return t.profile.occupation.listedCompany;
    case 'profile.occupation.businessOwner':
      return t.profile.occupation.businessOwner;
    case 'profile.occupation.publicOfficer':
      return t.profile.occupation.publicOfficer;
    case 'profile.occupation.clerk':
      return t.profile.occupation.clerk;
    case 'profile.occupation.secretary':
      return t.profile.occupation.secretary;
    case 'profile.occupation.consultant':
      return t.profile.occupation.consultant;
    case 'profile.occupation.foreignFinance':
      return t.profile.occupation.foreignFinance;
    case 'profile.occupation.student':
      return t.profile.occupation.student;
    case 'profile.occupation.apparelShop':
      return t.profile.occupation.apparelShop;
    case 'profile.occupation.salesPerson':
      return t.profile.occupation.salesPerson;
    case 'profile.occupation.foodIndustry':
      return t.profile.occupation.foodIndustry;
    case 'profile.occupation.cookNutritionist':
      return t.profile.occupation.cookNutritionist;
    case 'profile.occupation.nutritionist':
      return t.profile.occupation.nutritionist;
    case 'profile.occupation.customerService':
      return t.profile.occupation.customerService;
    case 'profile.occupation.beautyIndustry':
      return t.profile.occupation.beautyIndustry;
    case 'profile.occupation.beautician':
      return t.profile.occupation.beautician;
    case 'profile.occupation.esthetician':
      return t.profile.occupation.esthetician;
    case 'profile.occupation.beautyStaff':
      return t.profile.occupation.beautyStaff;
    case 'profile.occupation.lawyer':
      return t.profile.occupation.lawyer;
    case 'profile.occupation.notary':
      return t.profile.occupation.notary;
    case 'profile.occupation.administrativeNotary':
      return t.profile.occupation.administrativeNotary;
    case 'profile.occupation.taxAccountant':
      return t.profile.occupation.taxAccountant;
    case 'profile.occupation.socialInsuranceLaborLawyer':
      return t.profile.occupation.socialInsuranceLaborLawyer;
    case 'profile.occupation.publicAccountant':
      return t.profile.occupation.publicAccountant;
    case 'profile.occupation.medicalRelated':
      return t.profile.occupation.medicalRelated;
    case 'profile.occupation.nurse':
      return t.profile.occupation.nurse;
    case 'profile.occupation.doctor':
      return t.profile.occupation.doctor;
    case 'profile.occupation.dentist':
      return t.profile.occupation.dentist;
    case 'profile.occupation.pharmacist':
      return t.profile.occupation.pharmacist;
    case 'profile.occupation.dentalHygienist':
      return t.profile.occupation.dentalHygienist;
    case 'profile.occupation.pharmaceuticalRelated':
      return t.profile.occupation.pharmaceuticalRelated;
    case 'profile.occupation.architecturalRelated':
      return t.profile.occupation.architecturalRelated;
    case 'profile.occupation.architect':
      return t.profile.occupation.architect;
    case 'profile.occupation.interiorDesigner':
      return t.profile.occupation.interiorDesigner;
    case 'profile.occupation.interiorCoordinator':
      return t.profile.occupation.interiorCoordinator;
    case 'profile.occupation.realEstateRelated':
      return t.profile.occupation.realEstateRelated;
    case 'profile.occupation.entertainmentRelated':
      return t.profile.occupation.entertainmentRelated;
    case 'profile.occupation.celebrityModel':
      return t.profile.occupation.celebrityModel;
    case 'profile.occupation.artist':
      return t.profile.occupation.artist;
    case 'profile.occupation.eventCompanion':
      return t.profile.occupation.eventCompanion;
    case 'profile.occupation.sportsPlayer':
      return t.profile.occupation.sportsPlayer;
    case 'profile.occupation.childcare':
      return t.profile.occupation.childcare;
    case 'profile.occupation.transportationRelated':
      return t.profile.occupation.transportationRelated;
    case 'profile.occupation.pilot':
      return t.profile.occupation.pilot;
    case 'profile.occupation.driver':
      return t.profile.occupation.driver;
    case 'profile.occupation.cabinAttendant':
      return t.profile.occupation.cabinAttendant;
    case 'profile.occupation.mechanic':
      return t.profile.occupation.mechanic;
    case 'profile.occupation.advertisingRelated':
      return t.profile.occupation.advertisingRelated;
    case 'profile.occupation.designer':
      return t.profile.occupation.designer;
    case 'profile.occupation.creator':
      return t.profile.occupation.creator;
    case 'profile.occupation.tradingCompany':
      return t.profile.occupation.tradingCompany;
    case 'profile.occupation.insurance':
      return t.profile.occupation.insurance;
    case 'profile.occupation.realEstate':
      return t.profile.occupation.realEstate;
    case 'profile.occupation.telecommunication':
      return t.profile.occupation.telecommunication;
    case 'profile.occupation.engineer':
      return t.profile.occupation.engineer;
    case 'profile.occupation.finance':
      return t.profile.occupation.finance;
    case 'profile.occupation.distribution':
      return t.profile.occupation.distribution;
    case 'profile.occupation.travelRelated':
      return t.profile.occupation.travelRelated;
    case 'profile.occupation.massMedia':
      return t.profile.occupation.massMedia;
    case 'profile.occupation.welfareCare':
      return t.profile.occupation.welfareCare;
    case 'profile.occupation.bridal':
      return t.profile.occupation.bridal;
    case 'profile.occupation.education':
      return t.profile.occupation.education;
    case 'profile.occupation.factoryEngineer':
      return t.profile.occupation.factoryEngineer;
    case 'profile.occupation.illustrator':
      return t.profile.occupation.illustrator;
    case 'profile.occupation.influencer':
      return t.profile.occupation.influencer;
    case 'profile.occupation.agriculture':
      return t.profile.occupation.agriculture;
    case 'profile.occupation.fishery':
      return t.profile.occupation.fishery;
    case 'profile.occupation.other':
      return t.profile.occupation.other;
    case 'common.hyphen':
      return t.common.hyphen;

    // EducationalBackground
    case 'profile.educationalBackground.highSchool':
      return t.profile.educationalBackground.highSchool;
    case 'profile.educationalBackground.juniorCollege':
      return t.profile.educationalBackground.juniorCollege;
    case 'profile.educationalBackground.vocationalSchool':
      return t.profile.educationalBackground.vocationalSchool;
    case 'profile.educationalBackground.technicalCollege':
      return t.profile.educationalBackground.technicalCollege;
    case 'profile.educationalBackground.university':
      return t.profile.educationalBackground.university;
    case 'profile.educationalBackground.graduateSchool':
      return t.profile.educationalBackground.graduateSchool;
    case 'profile.educationalBackground.other':
      return t.profile.educationalBackground.other;

    // Sibling
    case 'profile.sibling.eldestSon':
      return t.profile.sibling.eldestSon;
    case 'profile.sibling.eldestDaughter':
      return t.profile.sibling.eldestDaughter;
    case 'profile.sibling.secondSon':
      return t.profile.sibling.secondSon;
    case 'profile.sibling.secondDaughter':
      return t.profile.sibling.secondDaughter;
    case 'profile.sibling.thirdSon':
      return t.profile.sibling.thirdSon;
    case 'profile.sibling.thirdDaughter':
      return t.profile.sibling.thirdDaughter;
    case 'profile.sibling.onlyChild':
      return t.profile.sibling.onlyChild;
    case 'profile.sibling.other':
      return t.profile.sibling.other;

    // Roommate
    case 'profile.roommate.livingAlone':
      return t.profile.roommate.livingAlone;
    case 'profile.roommate.livingWithParentsAndBrothers':
      return t.profile.roommate.livingWithParentsAndBrothers;
    case 'profile.roommate.livingWithFriends':
      return t.profile.roommate.livingWithFriends;
    case 'profile.roommate.livingWithPetsDog':
      return t.profile.roommate.livingWithPetsDog;
    case 'profile.roommate.livingWithPetsCat':
      return t.profile.roommate.livingWithPetsCat;
    case 'profile.roommate.livingWithPetsOther':
      return t.profile.roommate.livingWithPetsOther;

    // Sixteen Personality
    case 'profile.sixteen.istj':
      return t.profile.sixteen.istj;
    case 'profile.sixteen.isfj':
      return t.profile.sixteen.isfj;
    case 'profile.sixteen.infj':
      return t.profile.sixteen.infj;
    case 'profile.sixteen.intj':
      return t.profile.sixteen.intj;
    case 'profile.sixteen.istp':
      return t.profile.sixteen.istp;
    case 'profile.sixteen.isfp':
      return t.profile.sixteen.isfp;
    case 'profile.sixteen.infp':
      return t.profile.sixteen.infp;
    case 'profile.sixteen.intp':
      return t.profile.sixteen.intp;
    case 'profile.sixteen.estp':
      return t.profile.sixteen.estp;
    case 'profile.sixteen.esfp':
      return t.profile.sixteen.esfp;
    case 'profile.sixteen.enfp':
      return t.profile.sixteen.enfp;
    case 'profile.sixteen.entp':
      return t.profile.sixteen.entp;
    case 'profile.sixteen.estj':
      return t.profile.sixteen.estj;
    case 'profile.sixteen.esfj':
      return t.profile.sixteen.esfj;
    case 'profile.sixteen.enfj':
      return t.profile.sixteen.enfj;
    case 'profile.sixteen.entj':
      return t.profile.sixteen.entj;

    // HouseWork
    case 'profile.houseWork.activelyParticipate':
      return t.profile.houseWork.activelyParticipate;
    case 'profile.houseWork.willingToParticipate':
      return t.profile.houseWork.willingToParticipate;
    case 'profile.houseWork.shareEqually':
      return t.profile.houseWork.shareEqually;
    case 'profile.houseWork.preferPartnerHandle':
      return t.profile.houseWork.preferPartnerHandle;
    case 'profile.houseWork.partnerHandle':
      return t.profile.houseWork.partnerHandle;

    // DatingPreference
    case 'profile.datingPreference.dateSoon':
      return t.profile.datingPreference.dateSoon;
    case 'profile.datingPreference.dateIfCompatible':
      return t.profile.datingPreference.dateIfCompatible;
    case 'profile.datingPreference.messageBeforeDate':
      return t.profile.datingPreference.messageBeforeDate;

    // BodyType
    case 'profile.bodyType.slim':
      return t.profile.bodyType.slim;
    case 'profile.bodyType.slightlySlim':
      return t.profile.bodyType.slightlySlim;
    case 'profile.bodyType.average':
      return t.profile.bodyType.average;
    case 'profile.bodyType.glamorous':
      return t.profile.bodyType.glamorous;
    case 'profile.bodyType.muscular':
      return t.profile.bodyType.muscular;
    case 'profile.bodyType.slightlyChubby':
      return t.profile.bodyType.slightlyChubby;
    case 'profile.bodyType.chubby':
      return t.profile.bodyType.chubby;
    case 'profile.bodyType.unspecified':
      return t.profile.bodyType.unspecified;

    // SalaryRange
    case 'profile.salaryRange.under2m':
      return t.profile.salaryRange.under2m;
    case 'profile.salaryRange.twoTo4m':
      return t.profile.salaryRange.twoTo4m;
    case 'profile.salaryRange.fourTo6m':
      return t.profile.salaryRange.fourTo6m;
    case 'profile.salaryRange.sixTo8m':
      return t.profile.salaryRange.sixTo8m;
    case 'profile.salaryRange.eightTo10m':
      return t.profile.salaryRange.eightTo10m;
    case 'profile.salaryRange.tenTo15m':
      return t.profile.salaryRange.tenTo15m;
    case 'profile.salaryRange.fifteenTo20m':
      return t.profile.salaryRange.fifteenTo20m;
    case 'profile.salaryRange.twentyTo30m':
      return t.profile.salaryRange.twentyTo30m;
    case 'profile.salaryRange.over30m':
      return t.profile.salaryRange.over30m;

    // Sociability
    case 'profile.sociability.quickFriendship':
      return t.profile.sociability.quickFriendship;
    case 'profile.sociability.gradualFriendship':
      return t.profile.sociability.gradualFriendship;
    case 'profile.sociability.slowFriendship':
      return t.profile.sociability.slowFriendship;

    // PersonalityTrait
    case 'profile.personalityTrait.kind':
      return t.profile.personalityTrait.kind;
    case 'profile.personalityTrait.honest':
      return t.profile.personalityTrait.honest;
    case 'profile.personalityTrait.decisive':
      return t.profile.personalityTrait.decisive;
    case 'profile.personalityTrait.calm':
      return t.profile.personalityTrait.calm;
    case 'profile.personalityTrait.friendly':
      return t.profile.personalityTrait.friendly;
    case 'profile.personalityTrait.cheerful':
      return t.profile.personalityTrait.cheerful;
    case 'profile.personalityTrait.indoor':
      return t.profile.personalityTrait.indoor;
    case 'profile.personalityTrait.outdoor':
      return t.profile.personalityTrait.outdoor;
    case 'profile.personalityTrait.serious':
      return t.profile.personalityTrait.serious;
    case 'profile.personalityTrait.intelligent':
      return t.profile.personalityTrait.intelligent;
    case 'profile.personalityTrait.sincere':
      return t.profile.personalityTrait.sincere;
    case 'profile.personalityTrait.meticulous':
      return t.profile.personalityTrait.meticulous;
    case 'profile.personalityTrait.optimistic':
      return t.profile.personalityTrait.optimistic;
    case 'profile.personalityTrait.shy':
      return t.profile.personalityTrait.shy;
    case 'profile.personalityTrait.alwaysSmiling':
      return t.profile.personalityTrait.alwaysSmiling;
    case 'profile.personalityTrait.elegant':
      return t.profile.personalityTrait.elegant;
    case 'profile.personalityTrait.composed':
      return t.profile.personalityTrait.composed;
    case 'profile.personalityTrait.humble':
      return t.profile.personalityTrait.humble;
    case 'profile.personalityTrait.strict':
      return t.profile.personalityTrait.strict;
    case 'profile.personalityTrait.caring':
      return t.profile.personalityTrait.caring;
    case 'profile.personalityTrait.lonesome':
      return t.profile.personalityTrait.lonesome;
    case 'profile.personalityTrait.sociable':
      return t.profile.personalityTrait.sociable;
    case 'profile.personalityTrait.coolHeaded':
      return t.profile.personalityTrait.coolHeaded;
    case 'profile.personalityTrait.curious':
      return t.profile.personalityTrait.curious;
    case 'profile.personalityTrait.homely':
      return t.profile.personalityTrait.homely;
    case 'profile.personalityTrait.workaholic':
      return t.profile.personalityTrait.workaholic;
    case 'profile.personalityTrait.responsible':
      return t.profile.personalityTrait.responsible;
    case 'profile.personalityTrait.caringForOthers':
      return t.profile.personalityTrait.caringForOthers;
    case 'profile.personalityTrait.goodSpeaker':
      return t.profile.personalityTrait.goodSpeaker;
    case 'profile.personalityTrait.goodListener':
      return t.profile.personalityTrait.goodListener;
    case 'profile.personalityTrait.refreshing':
      return t.profile.personalityTrait.refreshing;
    case 'profile.personalityTrait.active':
      return t.profile.personalityTrait.active;
    case 'profile.personalityTrait.rational':
      return t.profile.personalityTrait.rational;
    case 'profile.personalityTrait.competitive':
      return t.profile.personalityTrait.competitive;
    case 'profile.personalityTrait.funny':
      return t.profile.personalityTrait.funny;
    case 'profile.personalityTrait.passionate':
      return t.profile.personalityTrait.passionate;
    case 'profile.personalityTrait.considerate':
      return t.profile.personalityTrait.considerate;
    case 'profile.personalityTrait.diligent':
      return t.profile.personalityTrait.diligent;
    case 'profile.personalityTrait.bold':
      return t.profile.personalityTrait.bold;
    case 'profile.personalityTrait.tolerant':
      return t.profile.personalityTrait.tolerant;
    case 'profile.personalityTrait.generous':
      return t.profile.personalityTrait.generous;
    case 'profile.personalityTrait.natural':
      return t.profile.personalityTrait.natural;
    case 'profile.personalityTrait.genuine':
      return t.profile.personalityTrait.genuine;
    case 'profile.personalityTrait.ownPace':
      return t.profile.personalityTrait.ownPace;
    case 'profile.personalityTrait.shyWithOppositeSex':
      return t.profile.personalityTrait.shyWithOppositeSex;
    case 'profile.personalityTrait.moody':
      return t.profile.personalityTrait.moody;

    default:
      return t.common.hyphen;
  }
}
