enum EditProfileField {
  nickname,
  birthday,
  residenceRegion,
  bloodType,
  birthplaceRegion,
  height,
  bodyType,
  occupation,
  workplaceRegion,
  salaryRange,
  educationalBackground,
  sibling,
  roommate,
  maritalHistory,
  childSituation,
  holidayType,
  userLanguages,
  drinkingAlcohol,
  smoking,
  sixteenPersonality,
  personalityTrait,
  sociability,
  marriageAspiration,
  childDesire,
  houseWork,
  datingPreference,
  firstDateCostPreference,
  firstDateLocationPreference,
  tags,
  tagCategory,
  introductory,
  photo,
  photoPreview,
  photoUpload,
}


