import 'package:econa_mobile_app/domains/repositories/gen/econa/master/regions.pb.dart';

// 共通で使用する都道府県リスト（Region を直接使用）
final List<Region> prefectureRegions = [
  Region(id: 1, name: '北海道'),
  Region(id: 2, name: '青森県'),
  Region(id: 3, name: '岩手県'),
  Region(id: 4, name: '宮城県'),
  Region(id: 5, name: '秋田県'),
  Region(id: 6, name: '山形県'),
  Region(id: 7, name: '福島県'),
  Region(id: 8, name: '茨城県'),
  Region(id: 9, name: '栃木県'),
  Region(id: 10, name: '群馬県'),
  Region(id: 11, name: '埼玉県'),
  Region(id: 12, name: '千葉県'),
  Region(id: 13, name: '東京都'),
  Region(id: 14, name: '神奈川県'),
  Region(id: 15, name: '新潟県'),
  Region(id: 16, name: '富山県'),
  Region(id: 17, name: '石川県'),
  Region(id: 18, name: '福井県'),
  Region(id: 19, name: '山梨県'),
  Region(id: 20, name: '長野県'),
  Region(id: 21, name: '岐阜県'),
  Region(id: 22, name: '静岡県'),
  Region(id: 23, name: '愛知県'),
  Region(id: 24, name: '三重県'),
  Region(id: 25, name: '滋賀県'),
  Region(id: 26, name: '京都府'),
  Region(id: 27, name: '大阪府'),
  Region(id: 28, name: '兵庫県'),
  Region(id: 29, name: '奈良県'),
  Region(id: 30, name: '和歌山県'),
  Region(id: 31, name: '鳥取県'),
  Region(id: 32, name: '島根県'),
  Region(id: 33, name: '岡山県'),
  Region(id: 34, name: '広島県'),
  Region(id: 35, name: '山口県'),
  Region(id: 36, name: '徳島県'),
  Region(id: 37, name: '香川県'),
  Region(id: 38, name: '愛媛県'),
  Region(id: 39, name: '高知県'),
  Region(id: 40, name: '福岡県'),
  Region(id: 41, name: '佐賀県'),
  Region(id: 42, name: '長崎県'),
  Region(id: 43, name: '熊本県'),
  Region(id: 44, name: '大分県'),
  Region(id: 45, name: '宮崎県'),
  Region(id: 46, name: '鹿児島県'),
  Region(id: 47, name: '沖縄県'),
];

int indexOfRegionById(List<Region> regions, int id) {
  return regions.indexWhere((r) => r.id == id);
}

