#!/bin/bash
# Generate a dummy env.g.dart file for CI builds
# This script creates a minimal env.g.dart with dummy values

ENV_G_DART="lib/presentations/env.g.dart"
DUMMY_VALUE="dummy_ci_value"

# Extract all field names from env.dart
FIELDS=$(grep -oP "static String \K\w+(?= = _Env\.)" lib/presentations/env.dart)

cat > "$ENV_G_DART" << 'HEADER'
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by scripts/generate_env_g_dart_for_ci.sh for CI builds

part of 'env.dart';

// CI dummy implementation
final class _Env {
HEADER

# Generate each field with a dummy value
for field in $FIELDS; do
    echo "  static const String $field = '$DUMMY_VALUE';" >> "$ENV_G_DART"
done

echo "}" >> "$ENV_G_DART"

echo "Generated $ENV_G_DART with $(echo "$FIELDS" | wc -w) fields"

